ablog/theblog/urls.py
from django.urls import path
from .views import (HomeView, ArticleDetailView, AddPostView, UpdatePostView, 
                                DeletePostView, AddCAtegoryView, category_view, likeView, AddCommentView)

app_name = "blog"

urlpatterns = [
    path('', HomeView.as_view() , name='home'),
    path('article/<int:pk>', ArticleDetailView.as_view(), name="article_detail"),
    path('add_post/', AddPostView.as_view(), name='add_post'),
    path('add_category/', AddCAtegoryView.as_view(), name='add_category'),
    path('article/edit/<int:pk>', UpdatePostView.as_view(), name="update_post"),
    path('article/<int:pk>/remove', DeletePostView.as_view(), name="delete_post"),
    path('category/<str:cats>/', category_view, name='category'),
    path('like/<int:pk>', likeView, name="like_post"),
    path('article/<int:pk>/comment', AddCommentView.as_view(), name='add_comment'),

]

ablog/theblog/templates/add_category.html
{% extends 'base.html' %}

{% block title %}Add CAtegory {% endblock %}
{% block content %}
{% if user.is_authenticated %}


<h1>Create a Category</h1>
<div class="form-group">
<form  method="POST">
        {% csrf_token %}

        {{ form.as_p }}
        <a class="btn btn-secondary" href="{% url 'blog:home' %}">To Home</a>
        <button class="btn btn-secondary">Create</button>

</form>

</div>

{% else %}
    <h3>You're not allowed here and yuh know it.</h3>
{% endif %}
    
{% endblock %}

ablog/theblog/templates/add_comment.html
{% extends 'base.html' %}

{% block title %}Add Comment {% endblock %}
{% block content %}
<style>
        .form-group {
            width: 70%;
            margin: 0 auto;
            background-color: #427D9D;
            border-radius: .2rem;
            padding: 20px;
        }
        .a_btn {
            display: flex;
            justify-content: flex-end;
        }
    </style>

<br>
<h1>Add a Comment</h1>
<div class="form-group">
<form  method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-secondary">Comment</button>

</form>

</div>
<br><br>
    
{% endblock %}

ablog/theblog/templates/article_details.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{ post.author.title }}
{% endblock %}

{% block content %}
<style>
    .post_details{
        width: 80%;
        /* background-color: #fff; */
        margin: 0 auto;
    }

    .image > img{
        width: 100%;
        border-radius: 1rem;
    }
    .post_details > .post_body{
        /* width: 95%; */
        /* background: #000; */
        padding: 1rem;
        margin: 0 auto;
        border-radius: 5px;
    }

    /* Comments */
    .card{
        background-color: #D0D4CA;
        color: #000;
        /* width: 95%; */
        margin: 0 auto;
    }
    .card-body, .card-header, .list-group-item{
        background-color: #D0D4CA;

    }

    /* Likes */
    .post_like_detail{
        display: flex;
        justify-content: space-between;
    }
    .likes{
        display: flex;
        justify-content: flex-end;
    }
    .user_stuff{
        display: flex;
        justify-content: flex-start;
        gap: 1rem;
    }

</style>

<br>
    <a href="{% url 'blog:home' %}">
        <img src="{% static 'theblog\images\undo.png' %}" alt="back button" width="40px" height="40px">
    </a>
    <h1>{{ post.title }}</h1>
    <small>By: {{ post.author.first_name }} {{ post.author.last_name }}</small>
    <br>
    <small>Date: {{ post.post_date }}</small>
    
    <div class="post_details">
        {% if user.is_authenticated %}

        <br>
        <div class="post_like_detail">  
            {% if user.id == post.author.id %}
            <div class="user_stuff">
                <a class="btn btn-secondary" href="{% url 'blog:update_post' post.pk %}">Edit</a>
                <a class="btn btn-secondary" href="{% url 'blog:delete_post' post.pk %}">Delete</a>
            </div>
        {% endif %}

        <br>
        <form action="{% url 'blog:like_post' post.pk %}" method="POST" class="likes">
            {% csrf_token %}
            {% if liked %}
                <button type="submit" name="post_id" value="{{ post.id }}" class="btn btn-primary btn-sm">
                    Dislike | {{ total_likes }}
                </button>
            {% else %}
                <button type="submit" name="post_id" value="{{ post.id }}" class="btn btn-primary btn-sm">
                    Like | {{ total_likes }}
                </button>
            {% endif %}
        </form>
        {% else %}
            <br>
            <br>
            <hr>
            <div class="likes">
                <button class="btn btn-primary ">{{ total_likes }} likes</button>
            </div>
        {% endif %}
    </div>
    


        <hr>
        {% if post.header_image %}
        <div class="image">
            <img src="{{ post.header_image.url }}">
            <br>
        </div>
        {% endif %}
        <br>
        <div class="post_body">
            {{ post.body | safe }}
        </div>
        <hr>
    
        <!-- <h2 class="mb-4">Comments</h2> -->
        <div class="card mb-4">
            <div class="card-header">
                <h5 class="mb-0">Comments</h5>
            </div>
            <div class="card-body">
                {% if not post.comments.all %}
                    <div class="alert alert-info">
                        <h4>No Comments to Show.</h4>
                        {% if user.is_authenticated %}
                            <a href="{% url 'blog:add_comment' post.pk %}">Add comment</a>
                        {% endif %}
                    </div>
                {% else %}
                    <ul class="list-group list-group-flush">
                        {% for comment in post.comments.all %}
                            <li class="list-group-item">
                                <strong>{{ comment.name }} - {{ comment.date_added }}</strong>
                                <p>{{ comment.body }}</p>
                            </li>
                        {% endfor %}
                    </ul>
                    <a href="{% url 'blog:add_comment' post.pk %}">Add comment</a>
                {% endif %}
            </div>
        </div>
        
    </div>



    <br>


    <br>
    <br>
    <br>
{% endblock %}

ablog/theblog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Postext{% endblock %}</title>


    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css">
    <!-- <link rel="stylesheet" href="./bootstrap-4.0.0/dist/css/bootstrap.min.css"> -->

    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
  />
</head>
<style>
  *{
    margin: 0;
    padding: 0;
  }
  body{

    background-color: #1B262C;
     color: #fff;
  }
</style>
<body>

{% include 'navbar.html' %}

<!-- Content Area -->
<div class="container">
    {% block content %}
    {% endblock %}
</div>

<!-- JavaScript -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"></script>
</body>
</html>

ablog/theblog/templates/categories.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Category: {{ cats }}{% endblock %}

{% block content %}
<style>
        /* Posts */
    .card{
        width: 90%;
        margin: 0 auto;
    }
    .card-body{
        background-color: #8DC6FF;
    }
    .card-text > a{
        color: #233142;
        font-weight: bold;
    }
    .card-text > a:hover{
        color: #4F709C;
        text-decoration: none;
    }

    .see{
        display: flex;
        justify-content: flex-start;
        align-items: center; 
        gap: 1rem;
    }

    body{
        font-family:  "IBM Plex Sans", monospace;
    }
    .nav_bar{
    animation: slideIn 0.8s ease-in-out;

    }
    @keyframes slideIn {
  0% {
    transform: translateX(-100%);
  }
  100% {
    transform: translateX(0);
  }
}


    h1{
        color: #fff;
    }

    /* Categor */
    .list-group-item{
        background-color: #2E79BA;
    }
    .list-group-item > a{
        color: white;
    }

    /* Posts */
    .card{
        border-width: 0;
    }
    .card-body{
        background-color: #1B262C;
        color: #fff;
        
   
    }
    .card-title > a{
        color: #fff;
        font-size: 2.5rem;
        font-weight: bold;
    }
    .card-text > a{
        color: #fff;
        font-size: 1.5rem;
    }
    .card-text > a:hover{
        color: #4F709C;
        text-decoration: none;
    }

</style>

{% if category_posts %}
    <br>
    <div class="see">
        <a href="{% url 'blog:home' %}">
            <img src="{% static 'theblog\images\undo.png' %}" alt="back button" width="40px" height="40px">
        </a>
        <h1>{{ cats }} Category</h1><br>
    </div>
    <br>
    <ul>
        {% for post in category_posts %}
        <div class="row mb-4">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body"> 
                        <h5 class="card-title">
                            <a href="{% url 'blog:article_detail' post.pk %}">{{ post.title }}</a>
                        </h5><hr>
                        <p class="card-text"><a href="{% url 'blog:article_detail' post.pk %}">{{ post.snippet }}</a></p><hr>
                        <!-- <p class="card-text">{{ post.body|slice:":200"| safe }}</p><hr> -->
                        <p class="card-text">
                            <small class="text-muted">
                                {{ post.author.first_name }} {{ post.author.last_name }} - 
                                {% if post.category %}
                                    <a href="{% url 'blog:category' post.category %}">{{ post.category }}</a>
                                {% else %}
                                    No Category Available
                                {% endif %}
                                - {{ post.post_date|date }}
                            </small>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    </ul>

{% else %} <br>
    <h3>Sorry this page does not exist.</h3>
    <br>
    <a href="{% url 'blog:home' %}" class="btn btn-grey">Home</a>
{% endif %}
{% endblock %}

ablog/theblog/templates/delete_post.html
{% extends 'base.html' %}

{% block title %}Delete Blog Post {% endblock %}
{% block content %}
{% if user.is_authenticated %}


<h1>Delete Post</h1><br>
<h3>Delete: {{ post.title }} </h3><br><hr>

<div class="form-group">
<form  method="POST">
        {% csrf_token %}
        <strong>Are yuh sure to delete?</strong><br><br>
        <a class="btn btn-secondary" href="{% url 'blog:article_detail' post.pk %}">Back</a>
        <button class="btn btn-secondary">Delete</button>

</form>

</div>
    
{% endif %}
{% endblock %}

ablog/theblog/templates/home.html
{% extends 'base.html' %}

{% block title %}Posts{% endblock %}
{% block style %}

{% endblock %}


{% block content %}


<style>
    body{
        font-family:  "IBM Plex Sans", monospace;
    }
    .nav_bar{
    animation: slideIn 0.8s ease-in-out;

    }
    @keyframes slideIn {
  0% {
    transform: translateX(-100%);
  }
  100% {
    transform: translateX(0);
  }
}


    h1{
        color: #fff;
    }

    /* Categor */
    .list-group-item{
        background-color: #2E79BA;
    }
    .list-group-item > a{
        color: white;
    }

    /* Posts */
    .card{
        border-width: 0;
    }
    .card-body{
        background-color: #1B262C;
        color: #fff;
        
   
    }
    .card-title > a{
        color: #fff;
        font-size: 2.5rem;
        font-weight: bold;
    }
    .card-text > a{
        color: #fff;
        font-size: 1.5rem;
    }
    .card-text > a:hover{
        color: #4F709C;
        text-decoration: none;
    }

</style>
    <br>
    
    <h1 >All Posts</h1><br>
    <div class="container see">
        <div class="row">
            <div class="col-md-2 categories-left" >
                <!-- Left Categories -->
                {% if cat_menu %}
                    <ul class="list-group" >
                        {% for item in cat_menu %}
                            <li class="list-group-item">
                                <a href="{% url 'blog:category' item %}">{{ item }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
            
            <div class="col-md-10 stuff">
                <!-- Posts Content -->
                {% for post in object_list %}
                    <div class="row mb-4">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-body"> 
                                    <h5 class="card-title">
                                        <a href="{% url 'blog:article_detail' post.pk %}">{{ post.snippet }}</a>
                                    </h5>
                                    <!-- <p class="card-text"><a href="{% url 'blog:article_detail' post.pk %}">{{ post.snippet }}</a></p> -->
                                    <p class="card-text">{{ post.body|slice:":200"| safe}}</p><hr>
                                    <p class="card-text">
                                        <small class="text-muted">
                                            {{ post.author.first_name }} {{ post.author.last_name }} - 
                                            {% if post.category %}
                                                <a href="{% url 'blog:category' post.category %}">{{ post.category }}</a>
                                            {% else %}
                                                No Category Available
                                            {% endif %}
                                            - {{ post.post_date }}
                                        </small>
                                    </p>
                                </div>
                            </div><br>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

ablog/theblog/templates/navbar.html
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark m-1" style="background-color: #1B262C; border-radius: 10px; margin-bottom: 20px; ">
    <div class="container-fluid col-md-11">
        <div class="navbar-header">
            <a class="navbar-brand animate__backInLeft" style="font-size: 2rem;" href="{% url 'landing:index' %}">Postext</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                                <!-- Categories Dropdown -->
                {% if cat_menu %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
                            Categories
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% for item in cat_menu %}
                                <a class="dropdown-item" href="{% url 'blog:category' item %}">{{ item }}</a> 
                            {% endfor %}
                        </div>
                    </li>
                {% endif %}
                <!-- User Authentication Links -->
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:add_post' %}">Add Post</a>
                    </li>                    
                    {% if user.is_staff %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blog:add_category' %}">Add Category</a>
                        </li>
                    {% endif %}
                    
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
                            Profile
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'members:edit_profile' %}">Edit Settings</a>
                            {% if profile.user.id %}
                                <a class="dropdown-item" href="{% url 'members:edit_profile_page' user.profile.id %}">Edit Profile</a>
                                <a class="dropdown-item" href="{% url 'members:show_profile_page' user.profile.id %}">Show Profile</a>
                            {% else %}
                                <a class="dropdown-item" href="{% url 'members:create_profile_page' %}">Create Profile Page</a>
                            {% endif %}
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>

                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'members:register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                {% endif %}


                
            </ul>
        </div>
    </div>
</nav>

ablog/theblog/templates/update_post.html
{% extends 'base.html' %}

{% block title %}Edit Post {% endblock %}
{% block content %}
{% if user.is_authenticated %}

        {% if user.id == post.author.id %}
        <h1>Update Post</h1>
        <div class="form-group">
        <form  method="POST">
                {% csrf_token %}
                {{ form.media }}
                {{ form.as_p }}
                <a class="btn btn-secondary" href="{% url 'blog:article_detail' post.pk %}">Back</a>
                <button class="btn btn-secondary">Update</button>
        </form>
        </div>

        {% else %}
        <br><br>
           <h3>Yuh're not allowed here and yuh know it.</h3>
        {% endif %}

{% endif %}
{% endblock %}